
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "algorithm.h"
#include "permutation.h"

// TODO: Change ints to their respective types (uint8/16/32/64)
int
load_carriers(BMPImage* carriers[MAX_CARRIERS], int n, char s_paths[MAX_CARRIERS][256]);

void
generate_table(uint8_t* table, int32_t width, int32_t height);

void
apply_xor(BMPImage* img, uint8_t* table, BMPImage* out);

void
assign_pixels(BMPImage* img, uint8_t* section, int k, int j);

int
evaluate_polynomial(uint8_t* coef_arr, int degree, int x);

void
process_shadows(uint8_t* shadows, int n, uint8_t* section, int k);

int
bits_for_k(int k);

void
modify_carriers(BMPImage* carriers[MAX_CARRIERS], int k, int n, uint8_t shadow_pixels[n], int section_num);

void
save_shadows(char s_paths[MAX_CARRIERS][256], BMPImage* carriers[MAX_CARRIERS], int n);

int
distribute(BMPImage* img, int k, int n, char s_paths[MAX_CARRIERS][256]) {
    BMPImage* carriers[MAX_CARRIERS];
    if (load_carriers(carriers, n, s_paths) == -1) {
        return -1;
    }

    /* 
        Step 1. 
        Take the XOR operation to a pre-defined random table R and O. 
        R is generated by a pseudo random number generator in advance. 
        Q denotes the randomized image.
    */
    uint8_t r_table[img->width * img->height];
    generate_table(r_table, img->width, img->height);

    BMPImage* r_img = (BMPImage*)malloc(sizeof(BMPImage)); // Q
    apply_xor(img, r_table, r_img);

    /*
        Step 2.
        Set the current processing section number j to 1.
    */
    int32_t section_num = 0;

    /*
        Step 3.
        Sequentially take r non-processed pixels, say a0, a1, a2,…, ar-1, of Q to form a sharing section j. 
        Without loss of generality, let the current processing section be the j-th section of the image, 
        and create a polynomial of degree r–1 as following:

        fj(x)=(a0+ a1x+ a2x2+…+ ar-1xr-1) mod 257.
    */
    int32_t img_size = r_img->width * r_img->height;

    /*
        Step 7. Increase j by 1. 
        Step 8. Repeat Steps 3 to 7 until all pixels of Q are processed. 
    */
    for (; section_num < img_size / k; section_num++) {
        uint8_t processed_section[k];
        assign_pixels(r_img, processed_section, k, section_num);

        /*
            Step 4. 
            Generate the n shadow pixels as Eq. 4. 
            fj(1), fj(2), fj(3),..., fj(n)

            Step 5. 
            If fj(x) = 256, let the first non-zero pixel of {a0, a1, a2 ,..., an-1} be decreased by 1,
            say a0 = a0 –1, and goto Step 4.
        */
        uint8_t shadow_pixels[n];
        process_shadows(shadow_pixels, n, processed_section, k);

        /*
            Step 6.
            Sequentially assign pixels generated in Step 4 to the j-th pixel of the n shadow images.
        */
        modify_carriers(carriers, k, n, shadow_pixels, section_num);
    }
    save_shadows(s_paths, carriers, n);
    return ERR_OK;
}

int
load_carriers(BMPImage* carriers[MAX_CARRIERS], int n, char s_paths[MAX_CARRIERS][256]) {
    for (int i = 0; i < n; i++) {
        carriers[i] = read_bmp(s_paths[i]);
        if (!carriers[i]) {
            // Clean up previously loaded images
            for (int prev = 0; prev < i; prev++) {
                free(carriers[prev]->data);
                free(carriers[prev]);
            }
            return -1;
        }
    }
    return 0;
}

// Random Table R
void
generate_table(uint8_t* table, int32_t width, int32_t height) {
    for (int i = 0; i < width * height; i++) {
        table[i] = nextChar();
    }
}

// Apply XOR operation to the image data with the random table
void
apply_xor(BMPImage* img, uint8_t* table, BMPImage* out) {
    out->width  = img->width;
    out->height = img->height;

    out->data = (uint8_t*)malloc(sizeof(uint8_t) * img->width * img->height);

    for (int i = 0; i < img->width * img->height; i++) {
        out->data[i] = img->data[i] ^ table[i];
    }
}

void
assign_pixels(BMPImage* img, uint8_t* pixels, int k, int j) {
    for (int i = 0; i < k; i++) {
        pixels[i] = img->data[k * j + i];
    }
}

int
evaluate_polynomial(uint8_t* coef_arr, int degree, int x) {
    uint32_t result = 0;
    // https://en.wikipedia.org/wiki/Horner%27s_method
    for (int i = degree; i >= 0; i--) {
        result = (result * x + coef_arr[i]) % 257;
    }
    return result % 257;
}

void
process_shadows(uint8_t* shadows, int n, uint8_t* section, int k) {
    char is_overflowing = 1;
    while (is_overflowing) {
        is_overflowing = 0;
        for (int x = 1; x <= n; x++) {
            int val = evaluate_polynomial(section, k - 1, x);

            /*
                Step 5. 
                If fj(x) = 256, let the first non-zero pixel of {a0, a1, a2 ,..., an-1} be decreased by 1,
                say a0 = a0 –1, and goto Step 4.
            */
            if (val == 256) {
                for (int i = 0; i < k; i++) {
                    if (section[i] > 0) {
                        section[i] -= 1;
                        break;
                    }
                }
                break;
            } else {
                shadows[x - 1] = (uint8_t)val;
            }
        }
    }
}

int
bits_for_k(int k) {
    int bits = 8 / k;
    if (8 % k != 0)
        bits++;
    if (bits <= 1)
        return 1;
    if (bits <= 2)
        return 2;
    return 4;
}

/*
    LOGIC:
    k=8,9,10    -> 1 LSB of 8 pixels is modified
    k=4,5,6,7   -> 2 LSB of 4 pixels are modified
    k=2,3       -> 4 LSB of 2 pixels are modified
*/
void
modify_carriers(BMPImage* carriers[MAX_CARRIERS], int k, int n, uint8_t shadow_pixels[n], int section_num) {
    int bits_per_pixel  = bits_for_k(k);
    int pixels_per_byte = 8 / bits_per_pixel;
    uint8_t mask        = (1 << bits_per_pixel) - 1;

    for (int i = 0; i < n; i++) {
        uint8_t target       = shadow_pixels[i];
        uint32_t pixel_start = section_num * pixels_per_byte;

        for (int bit_group = 0; bit_group < pixels_per_byte; bit_group++) {
            uint32_t pixel_idx = pixel_start + bit_group;

            int shift    = 8 - bits_per_pixel * (bit_group + 1);
            uint8_t bits = (target >> shift) & mask;

            carriers[i]->data[pixel_idx] =
              (carriers[i]->data[pixel_idx] & ~mask) | bits;
        }
    }
}

void
save_shadows(char s_paths[MAX_CARRIERS][256], BMPImage* carriers[MAX_CARRIERS], int n) {
    for (int i = 0; i < n; i++) {
        char out_filename[32];
        snprintf(out_filename, sizeof(out_filename), "s_%d.bmp", i + 1);

        write_bmp(carriers[i], out_filename);
        write_shadow_metadata(out_filename, seed, i);
        // write_bmp(carriers[i], s_paths[i]);
        // write_shadow_metadata(s_paths[i], seed, i);
    }
}
