#include "bmp.h"
#include "permutation.h"
#include <stdint.h>

// Random Table R
void
generate_table(uint8_t* table, int32_t width, int32_t height) {
    for (int i = 0; i < width * height; i++) {
        table[i] = nextChar();
    }
}

// Apply XOR operation to the image data with the random table
void
apply_xor(BMPImage* img, uint8_t* table, BMPImage* out) {
    out->width  = img->width;
    out->height = img->height;

    out->data = (uint8_t*)malloc(sizeof(uint8_t) * img->width * img->height);

    for (int i = 0; i < img->width * img->height; i++) {
        out->data[i] = img->data[i] ^ table[i];
    }
}

void
assign_pixels(BMPImage* img, uint8_t** section, int k, int j) {
    for (int i = 0; i < k; i++) {
        section[i] = img->data[k * j + i];
    }
}

int
evaluate_polynomial(uint8_t* coef_arr, int degree, int x) {
    uint32_t result = 0;
    for (int i = 0; i <= degree; i++) {
        result += coef_arr[i] * pow(x, i);
    }
    return result % 257;
}

void
distribute(BMPImage* img, int k, int n) {
    /* 
        Step 1. 
        Take the XOR operation to a pre-defined random table R and O. 
        R is generated by a pseudo random number generator in advance. 
        Q denotes the randomized image.
    */
    uint8_t r_table[img->width * img->height];
    generate_table(r_table, img->width, img->height);

    BMPImage* r_img = (BMPImage*)malloc(sizeof(BMPImage)); // Q
    apply_xor(img, r_table, r_img);

    /*
        Step 2.
        Set the current processing section number j to 1.
    */
    int section_num = 0;

    /*
        Step 3.
        Sequentially take r non-processed pixels, say a0, a1, a2,…, ar-1, of Q to form a sharing section j. 
        Without loss of generality, let the current processing section be the j-th section of the image, 
        and create a polynomial of degree r–1 as following:

        fj(x)=(a0+ a1x+ a2x2+…+ ar-1xr-1) mod 257.
    */
    uint32_t img_size = r_img->width * r_img->height;

    for (; section_num < img_size / k; section_num++) {
        uint8_t* processed_section[k];
        // Get a0, a1, a2,…, ar-1 from the image
        uint8_t coef_arr[k];
        for (int i = 0; i < k; i++) {
            coef_arr[i] = r_img->data[section_num * k + i];
        }
        // Calculate f(1), f(2), ..., f(n)
        uint8_t to_apply_shadows[n];
        for (int i = 0; i < n; i++) {
            to_apply_shadows[i] = evaluate_polynomial(coef_arr, k - 1, i + 1);
        }

        // Apply the permutation to the shadows
        for (int i = 0; i < n; i++) {
            permute_shadows(to_apply_shadows[i]);
        }
    }
}